# Define input_slider
input_slider:
  target_temp:
    name: Target Heater Temperature Slider
    min: 5
    max: 30
    step: 1
    unit_of_measurement: step  
    icon: mdi:target

automation:
   # This automation script runs when the target temperature slider is moved.
   # It publishes its value to the same MQTT topic it is also subscribed to
   # The message is json format
  - alias: Temp slider moved
    trigger:
      platform: state
      entity_id: input_slider.target_temp
    action:
      service: mqtt.publish
      data_template:
        topic: "rfmOut/146/250/2"
        retain: true
        payload: "{\"t_0\":\"{{ states.input_slider.target_temp.state | int }}\"}"